# Generated by Django 3.1.5 on 2021-01-20 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_auto_20210120_1213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='updated_date',
            new_name='update_date',
        ),
    ]
