# Generated by Django 3.1.5 on 2021-01-20 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_auto_20210120_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.URLField(default='https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.webmasterpro.de%2Fcoding%2Farticle%2Fframework-django-konventionen.html&psig=AOvVaw1M9yqS3Ssaxns61eMMQpUh&ust=1611224927907000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCJjyzOWmqu4CFQAAAAAdAAAAABAD', max_length=400),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('d', 'draft'), ('p', 'published')], default='d', max_length=10),
        ),
    ]
