# Generated by Django 3.1.5 on 2021-01-20 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='updated_date',
            new_name='update_date',
        ),
    ]
